server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/Projects/vapers-config
        git:
          uri: https://github.com/JENOSS/vapers-config


management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh